version: "3"

services:
  # himatro-api:
  #   build: .
  #   depends_on:
  #     - postgres
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "./.env:/app/.env"
  #     - "/var/log/request_himatro_api.log.json:/app/request_himatro_api.log.json"
  #     - "/var/log/error_himatro_api.log:/app/error.log"
  #     - "./private_data/:/app/private_data/"

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=lucky
      - POSTGRES_PASSWORD=lucky123
      - POSTGRES_DB=himatro
    volumes:
      - /var/lib/postgresql/himatro_api_postgres_data:/var/lib/postgresql/data
    ports:
      - "54132:5432"
