version: '3'

services:
  himatro-api:
    build: .
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=lucky
      - POSTGRES_PASSWORD=lucky123
      - POSTGRES_DB=himatro
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "54132:5432"
    